name: meu_app_notificacoes
description: App de notificações locais personalizado

environment:
  sdk: '^3.7.0'



dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^16.1.0

flutter:
  uses-material-design: true
